dist: trusty
language: c
compiler:
  - gcc

before_install:
  - test -n $CC && unset CC
  - chmod +x bootstrap
  - ./bootstrap
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SvQhl2ydeyc16Tl1JNdBFMb9SdE/cGnn+wx7RQqWcmUUtRS7AFgXWj03G93OsA9VTxOeE1vyihRP8mcV3i9kO38FXkiqkNY1W/m4zOU6D8eMPOt0tBh3W1d7mUN4WqOgXC4VnKHicXDxEdN9Npw39B2cDqGLw6vSeyRqHPlHvFFnGZvz6chzcmokyE5BKQ2XgDDgoLhp+SOKFDOE57cwRVGpTAV34HdwSuesvagkH5NuRum3ObiQPr0OvhlTeXjE0fVRyNO5Q7ZNo0zg0eBx4+QSljiUcrtFnuV8JSu9fB3Yx1Qp4Z8CCGA7lEwurSGfgshhSon+X7vvHXdgyH7qM+AHYZuZEL/A5/GJi7tn/f1SBztb8Gj7zcuVPgsFJZaTKsuJ6/qcnUJpV8LfLN/ONbFd0ng22SABISB6DaSlsy2s6gN5OMiqe/DX70zGAEHnyZpw4HKMzmqXsxrIegi97KnPgcrrigSjYo4VTSOex8aL4nMbqtcAbDNCj7pGHnNBKDCjSS5J1IEMW2zGgL1AXsQwDUZxvRl3xzrS383ITVyyNBEdaa1zHEKXpYuTfVJoNpmQ3WpT/X38L0/hkfzNSh+de43hylsKa96kpeIkMHWee7rJiQZtP1zKAShi0W2ndt1I0+JAxvW/AcQatT25J/5dZpgm9xmyWetQ6r9PeBw="

addons:
  coverity_scan:
    project:
      name: "mmacala/benchmark_local"
      description: "<Your project description here>"
    notification_email: marco.macala@gmail.com
    build_command_prepend: ""
    build_command: "make"
    branch_pattern: coverity_scan

